### PR TITLE
add blob sveltekit example

### PR DESCRIPTION
**Pull request by correttojs**
### Description

- add blob sveltekit starter 

Screenshot 2023-05-05 at 10 59 49

### Type of Change

- [ ] New Example
- [ ] Example updates (Bug fixes, new features, etc.)
- [ ] Other (changes to the codebase, but not to examples)

### New Example Checklist

- [ ] 🛫 `npm run new-example` was used to create the example
- [ ] 📚 The template wasn't used but I carefuly read the [Adding a new example](https://github.com/vercel/examples#adding-a-new-example) steps and implemented them in the example
- [ ] 📱 Is it responsive? Are mobile and tablets considered?

### CODE REVIEW

**Comment by correttojs** [comment]
> Hey! Taking a look at this now – two points of feedback:
> 
> 1. Can we make sure the UI matches https://blob-starter.vercel.app/?
> 2. I keep getting `Error: BLOB_READ_WRITE_TOKEN environment variable is not set. Please set it to your write token.` despite setting the `BLOB_READ_WRITE_TOKEN` env var in `.env` and `.env.local` – how do I get this to work?

2. On a Preview env or in Prod it should work. Locally I was able to run it overriding the `vite.config.ts`
```
import { sveltekit } from "@sveltejs/kit/vite";
import { defineConfig, loadEnv } from "vite";

/** @type {import('vite').UserConfig} */
export default ({ mode }) => {
  process.env.BLOB_READ_WRITE_TOKEN = "vercel_blob_rw_...";
  return defineConfig({
    plugins: [sveltekit()],
  });
};
```

**Comment by correttojs** [comment]
hey @steven-tey , I tried to match the Nextjs template. It's the first time I write svelte code, so I didn't handle all the dynamic states (toasts, loading)

**Review by StephDietz — COMMENTED** [review]
Looks great! After uploading a file, should we reset the UI so they can upload another? Right now the button remains "Confirm Upload" even after it has already been uploaded

**Comment by correttojs** [comment]
> Looks great! After uploading a file, should we reset the UI so they can upload another? Right now the button remains "Confirm Upload" even after it has already been uploaded

Thanks for the feedback @StephDietz ! I reset the UI after the upload, though I'm not sure what are the next steps to release the template. could you help me with that 🙏?

**Pull request merged**
