### PR TITLE
Edge: disambiguate middleware and edge functions

### PR DESCRIPTION
**Pull request by ethomson**
### Description

The Edge Middleware examples were defined in `edge-functions`, which meant that the Edge Functions examples were defined in `edge-api-routes`. Update these to their proper names, moving `edge-functions` -> `edge-middleware` and `edge-api-routes` -> `edge-functions`.

This change also updates the front matter and `npm` / `yarn` instructions for demos.

### Type of Change

- [ ] New Example
- [x] Example updates (Bug fixes, new features, etc.)
- [ ] Other (changes to the codebase, but not to examples)

### Examples Checklist (@okbel edit)

| Example                            	| Demo URL 	| Check FrontMatter 	| Layout 	| Example Readme 	|
|------------------------------------	|----------	|-------------------	|--------	|----------------	|
| 'ab-testing-google-optimize',      	|          	|                   	|        	|                	|
| 'ab-testing-simple',               	|          	|                   	|        	|                	|
| 'ab-testing-statsig',              	|          	|                   	|        	|                	|
| 'add-header',                      	|          	|                   	|        	|                	|
| 'api-rate-limit',                  	|          	|                   	|        	|                	|
| 'api-rate-limit-and-tokens',       	|          	|                   	|        	|                	|
| 'basic-auth-password',             	|          	|                   	|        	|                	|
| 'bot-protection-botd',             	|          	|                   	|        	|                	|
| 'bot-protection-datadome',         	|          	|                   	|        	|                	|
| 'clerk-authentication',            	|          	|                   	|        	|                	|
| 'cookies',                         	|          	|                   	|        	|                	|
| 'cors',                            	|          	|                   	|        	|                	|
| 'crypto',                          	|          	|                   	|        	|                	|
| 'feature-flag-apple-store',        	|          	|                   	|        	|                	|
| 'feature-flag-configcat',          	|          	|                   	|        	|                	|
| 'feature-flag-optimizely',         	|          	|                   	|        	|                	|
| 'feature-flag-posthog',            	|          	|                   	|        	|                	|
| 'feature-flag-split',              	|          	|                   	|        	|                	|
| 'geolocation',                     	|          	|                   	|        	|                	|
| 'geolocation-country-block',       	|          	|                   	|        	|                	|
| 'hostname-rewrites',               	|          	|                   	|        	|                	|
| 'i18n',                            	|          	|                   	|        	|                	|
| 'image-response',                  	|          	|                   	|        	|                	|
| 'ip-blocking',                     	|          	|                   	|        	|                	|
| 'ip-blocking-datadome',            	|          	|                   	|        	|                	|
| 'ip-manual-blocking',              	|          	|                   	|        	|                	|
| 'json-response',                   	|          	|                   	|        	|                	|
| 'jwt-authentication',              	|          	|                   	|        	|                	|
| 'maintenance-page',                	|          	|                   	|        	|                	|
| 'next-news',                       	|          	|                   	|        	|                	|
| 'personalization-builder-io',      	|          	|                   	|        	|                	|
| 'power-parity-pricing',            	|          	|                   	|        	|                	|
| 'power-parity-pricing-strategies', 	|          	|                   	|        	|                	|
| 'query-params-filter',             	|          	|                   	|        	|                	|
| 'redirects-upstash',               	|          	|                   	|        	|                	|
| 'rewrites-upstash',                	|          	|                   	|        	|                	|
| 'user-agent-based-rendering'       	|          	|                   	|        	|                	|

### CODE REVIEW

**Review by lfades — CHANGES_REQUESTED** [review]
Blocking because we need to be careful while moving all examples.

@ethomson @leerob is this priority before the release? I think no as we can make updates on the position of the examples later on.

Here are the other things we need to migrate:

- Every Vercel project (usually every example has one) has to update its root directory to the right directory and its ignored build step in git settings
- We need to update the GH actions we currently have for moving the templates to Contentful, it updates them based on the path of the example, so this changes are going to duplicate examples if it's merged, and it currently doesn't handle removing examples (that we do manually)
- I understand we have links to this place from the docs in vercel.com, and we might have links to examples from other places, plus the many times we have shared them with customers

Overall I think we should wait on a change like this, and we need to change how we view the folders here, it doesn't really matter too much where we put them, it matters more how we show them, that being the Templates Marketplace, and we could also use other areas, like the main readme, that we can more easily change.

**Comment by feugy** [comment]
The e2e test suite of edge-function repo (both on PR and scheduled) is pulling some of these examples. 
Please let the @vercel/edge-compute team know when this will land, so we can adjust our e2e tests (preparation work [here](https://github.com/vercel/edge-functions/pull/431))

**Comment by lfades** [comment]
@ethomson This PR can break multiple things as we can't have a proper redirect for the examples that were moved, can we close this PR?

**Comment by ethomson** [comment]
We should not break our own links -- we should ensure that we're fixing the marketplace and such, but also, @manovotny has been working to improve the way our examples are displayed and reduce our dependency on GitHub.

We expect that we will break some external links - this [has been discussed](https://vercel.slack.com/archives/C0289CGVAR2/p1656342644633979) [a few times](https://vercel.slack.com/archives/C0289CGVAR2/p1661530842984969) and: matching our example names with our product names is incredibly important, and [solves a real customer problem](https://vercel.slack.com/archives/C0290CZ3U6Q/p1674234937715169).

**Comment by manovotny** [comment]
We can close this PR. I'll be handling it a different way.

**Pull request closed without merging**
